# Generated by Django 4.2.29 on 2026-04-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_on'], name='product_pro_created_37a585_idx'),
        ),
    ]
