"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import sys
from .database import DATABASE_CONFIG

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)dgstrhrxdj&@9dw&9blylj7jf$mtut4i5dmh(_dt2cxl2*n8h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
ENVIRONMENT = config('ENVIRONMENT')
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'admin_confirm',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'product',
    'authenticate',
    'users',
    'cart',
    'oauth2_provider'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    # For Landing Page/Apps
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
        'authenticate.throttling.CustomAnonRateThrottle'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_RATES': {
        'otp': '3/min',
        'anon': '6/min',
        'login': '5/d',
        'resend_and_verify_otp': '5/d',
        'reset_pwd': '5/d',
        'gift_resend': '3/day',
        'resend_otp': '5/day',
        'verify_otp': '5/day',
        'forgot_pwd': '5/day',
        'checkout': '10/min',
    },

    'NUM_PROXIES': 2

}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = DATABASE_CONFIG

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
AUTH_USER_MODEL = 'users.User'
ADMIN_USERNAME = config('ADMIN_USER_NAME')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ROOT_DIR = os.path.dirname(BASE_DIR)

SPECTACULAR_SETTINGS = {
    'TITLE': 'Ecom Marketplace API',
    'DESCRIPTION': (
        'A multi-merchant e-commerce platform.\n\n'
        '**Auth flow:**\n'
        '1. Register as a Buyer (`/user/api/v1/profile/`) or Merchant (`/user/api/v1/business-registration/`)\n'
        '2. Login (`/auth/api/v1/login/`) → receive `otp_session`\n'
        '3. Verify OTP (`/auth/api/v1/verify-otp/`) → receive `access` + `refresh` JWT tokens\n'
        '4. Use `Authorization: Bearer <access>` on all protected endpoints\n'
        '5. Refresh token at `/user/api/v1/token/refresh/` before 10-minute expiry\n\n'
        '**Roles:**\n'
        '- **Buyer** — browse products, manage cart, checkout, pay, track orders\n'
        '- **Merchant** — create/manage products, view & update orders for their store'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Auth', 'description': 'Login, OTP verification, token refresh'},
        {'name': 'Users', 'description': 'Registration and profile management'},
        {'name': 'Products', 'description': 'Product catalog — public browsing'},
        {'name': 'Merchant', 'description': 'Merchant-only: product management and order dashboard'},
        {'name': 'Cart', 'description': 'Cart management for buyers'},
        {'name': 'Orders', 'description': 'Checkout, order history, and payment'},
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'displayRequestDuration': True,
        'filter': True,
    },
}
